[package]
name       = "spack"
description = "Summon spack from rust build scripts!"
version = "0.0.0"
edition = "2021"
license = "(Apache-2.0 OR MIT)"
repository = "https://github.com/cosmicexplorer/spack-rs"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto                     = true

[dependencies]
async-process = "1.3.0"
displaydoc = { git = "https://github.com/yaahc/displaydoc", rev = "7159bb5c9d41ca3c7ccf04ae86ae3acb0ea12a27" }
flate2 = "1.0"
futures-core = "0.3.15"
futures-lite = "1"
hex = "0.4.3"
hex-literal = "0.3.4"
lazy_static = "1.4.0"
regex = "1"
reqwest = "0.11.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10.2"
signal-hook = "0.3.13"
tar = "0.4"
thiserror = "1.0.30"

[dev-dependencies]
tempdir = "0.3.7"
tokio-test = "0.4.2"
