[package]
name                    = "hyperscan-async"
description             = "Async wrapper for the hyperscan C++ regex library."
version                 = "0.0.1"
edition.workspace       = true
license                 = "BSD-3-Clause"
repository.workspace    = true
authors.workspace       = true

[features]
default                 = ["static", "compile"]
static                  = ["hyperscan-async-sys/static"]
compile                 = ["hyperscan-async-sys/compile"]
dynamic                 = ["hyperscan-async-sys/dynamic"]
chimera                 = ["hyperscan-async-sys/chimera"]

[lib]
name                    = "hyperscan"

[dependencies]
hyperscan-async-sys.workspace = true

async-stream.workspace  = true
cfg-if                  = "1"
displaydoc.workspace    = true
futures-core.workspace  = true
futures-util.workspace  = true
libc.workspace          = true
num_enum.workspace      = true
once_cell.workspace     = true
parking_lot.workspace   = true
static_assertions.workspace = true
thiserror.workspace     = true
tokio                   = { workspace = true, features = ["rt", "sync", "io-util", "macros"] }
tokio-stream            = "0.1.14"

[dev-dependencies]
eyre.workspace          = true
tokio                   = { workspace = true, features = ["macros"] }
tokio-test.workspace    = true

[lints]
workspace               = true

[package.metadata.docs.rs]
all-features            = true
rustdoc-args            = ["--cfg", "docsrs"]
