[package]
name                    = "hyperscan-async"
description             = "Async wrapper for the hyperscan C++ regex library."
version                 = "0.0.0"
edition                 = "2021"
license                 = "BSD-3-Clause"
repository.workspace    = true
authors.workspace       = true

[package.metadata.spack]
env_label               = "hyperscan-runtime-deps"
spec                    = "hyperscan@v5.4.2"

[package.metadata.spack.deps.hyperscan]
type                    = "static"
lib_names               = ["hs"]

[build-dependencies]
bindgen.workspace       = true
eyre.workspace          = true
spack.workspace         = true
tokio                   = { workspace = true, features = ["rt-multi-thread", "macros"] }

[dependencies]
async-stream.workspace  = true
displaydoc.workspace    = true
futures-core.workspace  = true
futures-util.workspace  = true
libc.workspace          = true
num_enum.workspace      = true
once_cell.workspace     = true
parking_lot.workspace   = true
static_assertions.workspace = true
thiserror.workspace     = true
tokio                   = { workspace = true, features = ["rt", "sync", "io-util"] }
tokio-stream            = "0.1.14"

[dev-dependencies]
eyre.workspace          = true
tokio                   = { workspace = true, features = ["macros"] }
tokio-test.workspace    = true

[lints]
workspace               = true
