[package]
name                    = "re2"
description             = "Wrapper for the re2 C++ regex library."
version                 = "0.0.0"
edition.workspace       = true
license                 = "BSD-3-Clause"
repository.workspace    = true
authors.workspace       = true

[package.metadata.spack]
env_label               = "re2-runtime-deps"
spec                    = "re2@2023-11-01~shared ^ abseil-cpp+shared"
static_libs             = ["re2"]
shared_libs             = ["abseil-cpp"]
cxx                     = "c++17"
bindings_allowlist      = ["absl::*", "re2::.*"]
header_path             = "src/re2.hpp"
bindings_output_path    = "src/bindings.rs"

[build-dependencies]
bindgen                 = "0.69.1"
eyre.workspace          = true
futures-util.workspace  = true
super-process.workspace = true
spack.workspace         = true
tokio                   = { workspace = true, features = ["macros"] }
