[package]
name                    = "re2"
description             = "Wrapper for the re2 C++ regex library."
version                 = "0.0.0"
edition.workspace       = true
license                 = "BSD-3-Clause"
repository.workspace    = true
authors.workspace       = true

[build-dependencies]
bindgen                 = "0.69.1"
eyre.workspace          = true
futures-util.workspace  = true
spack.workspace         = true
tokio                   = { workspace = true, features = ["macros"] }
