[package]
name                    = "super-process"
description             = "An async process creation framework."
authors                 = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]
license                 = "GPL-3.0-or-later"
repository              = "https://github.com/cosmicexplorer/super-process"
version                 = "0.0.0"
edition                 = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process           = "1.3.0"
async-trait             = "0.1.41"
displaydoc              = { git = "https://github.com/yaahc/displaydoc", rev = "7159bb5c9d41ca3c7ccf04ae86ae3acb0ea12a27" }
futures-lite            = "1"
indexmap                = "1.8.1"
lazy_static             = "1.4.0"
signal-hook             = "0.3.13"
tempfile                = "3.3.0"
thiserror               = "1.0.30"
tokio                   = { version = "1", features = ["full"] }

[dev-dependencies]
tokio-test              = "0.4.2"
